[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/remix-adapter"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/remix"
  status = 200
