[build]
  command = "npm run build"
  publish = "build/client"
  functions = "build/server"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/remix"
  status = 200
